### PR TITLE
[WIP] Implementation of BSC algorithm

### PR DESCRIPTION
**Pull request by pkj-m**
As discussed in the slack channel, I am working on the implementation of the Backtracking Sequential Coloring algorithm, which gives an exact coloring of the input graph (ref: https://www.researchgate.net/publication/292100744_Graph_coloring_algorithms).

The output of the program, however is not as expected, possibly due to implementation errors on my part, most probably due to different indexing schemes followed in the paper and in Julia.

### CODE REVIEW

**Comment by matbesancon** [comment]
@pkj-m for package structure:
- all files should be `include()`-ed in the main module file `SparseDiffTools.jl`
- add some tests for the algorithm

**Comment by pkj-m** [comment]
I was planning to keep this on hold for a while since we won't be using this algorithm in most of the cases (returns exact coloring which might be painfully slow for larger graphs). Will probably come back to this after phase one evaluation is over.

**Comment by matbesancon** [comment]
Ok, then these tips are still valid for your next PR

**Comment by matbesancon** [comment]
@pkj-m why close this?

**Comment by pkj-m** [comment]
I pushed the code through the other coloring algos PR. I thought it'll be better to keep it all in one place?

**Comment by matbesancon** [comment]
Usually better keep small PRs, it helps tracking things and seeing small diffs

**Comment by pkj-m** [comment]
Should I reopen this and delete the BSC commit from the other PR then?

**Comment by matbesancon** [comment]
I guess yes

**Comment by pkj-m** [comment]
Closing as discussed.

**Pull request closed without merging**
