### PR TITLE
Fix for new BlockBandedMatrices

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
`nblocks` changed as well?

https://github.com/JuliaDiffEq/ArrayInterface.jl/blob/master/src/ArrayInterface.jl#L430-L431

**Comment by dlfivefifty** [comment]
Yes: it was a complete redesign to incorporate the block structure in the axes

**Comment by ChrisRackauckas** [comment]
It looks like the use of blocklengths is an issue?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaArrays/BlockArrays.jl/pull/95/files#diff-f296e38172e8384204314bcecde8499aR27-R29

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/pull/84 and https://github.com/JuliaDiffEq/ArrayInterface.jl/pull/34 are the latest movements

**Comment by ChrisRackauckas** [comment]
It looks like the latest test found an issue:  getindex from Cartesians is trying to call `similar` with 3 arguments and tuples, but that doesn't seem to exist.

```julia
  Got exception outside of a @test
  LoadError: MethodError: no method matching similar(::BlockBandedMatrices.BlockSkylineMatrix{Float64,Array{Float64,1},BlockBandedMatrices.BlockSkylineSizes{Tuple{BlockArrays.BlockedUnitRange{Array{Int64,1}},BlockArrays.BlockedUnitRange{Array{Int64,1}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},BandedMatrices.BandedMatrix{Int64,Array{Int64,2},Base.OneTo{Int64}},Array{Int64,1}}}, 
::Type{Float64}, ::Tuple{Base.IdentityUnitRange{BlockArrays.BlockedUnitRange{Array{Int64,1}}},Base.OneTo{Int64}})
  Closest candidates are:
    similar(!Matched::BlockArrays.BlockArray, ::Type{T}, ::Tuple{Union{Colon, Integer, Base.IdentityUnitRange, Base.OneTo, UnitRange},Vararg{Union{Colon, Integer, Base.IdentityUnitRange, Base.OneTo, UnitRange},N} where N}) where T at C:\Users\accou\.julia\packages\BlockArrays\FxyhD\src\blockarray.jl:353
    similar(::BlockBandedMatrices.BlockSkylineMatrix, ::Type) at C:\Users\accou\.julia\packages\BlockBandedMatrices\ROxFN\src\BlockSkylineMatrix.jl:252
    similar(::BlockBandedMatrices.BlockSkylineMatrix, ::Type, !Matched::BlockBandedMatrices.BlockSkylineSizes) at C:\Users\accou\.julia\packages\BlockBandedMatrices\ROxFN\src\BlockSkylineMatrix.jl:252
    ...
  Stacktrace:
   [1] similar(::BlockBandedMatrices.BlockSkylineMatrix{Float64,Array{Float64,1},BlockBandedMatrices.BlockSkylineSizes{Tuple{BlockArrays.BlockedUnitRange{Array{Int64,1}},BlockArrays.BlockedUnitRange{Array{Int64,1}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},BandedMatrices.BandedMatrix{Int64,Array{Int64,2},Base.OneTo{Int64}},Array{Int64,1}}}, ::Tuple{Base.IdentityUnitRange{BlockArrays.BlockedUnitRange{Array{Int64,1}}},Base.OneTo{Int64}}) at C:\Users\accou\.julia\packages\BlockArrays\FxyhD\src\abstractblockarray.jl:38
   [2] _unsafe_getindex(::IndexCartesian, ::BlockBandedMatrices.BlockSkylineMatrix{Float64,Array{Float64,1},BlockBandedMatrices.BlockSkylineSizes{Tuple{BlockArrays.BlockedUnitRange{Array{Int64,1}},BlockArrays.BlockedUnitRange{Array{Int64,1}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},BandedMatrices.BandedMatrix{Int64,Array{Int64,2},Base.OneTo{Int64}},Array{Int64,1}}}, ::Base.Slice{BlockArrays.BlockedUnitRange{Array{Int64,1}}}, ::Array{Int64,1}) at .\multidimensional.jl:682
   [3] _getindex(::IndexCartesian, ::BlockBandedMatrices.BlockSkylineMatrix{Float64,Array{Float64,1},BlockBandedMatrices.BlockSkylineSizes{Tuple{BlockArrays.BlockedUnitRange{Array{Int64,1}},BlockArrays.BlockedUnitRange{Array{Int64,1}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},BandedMatrices.BandedMatrix{Int64,Array{Int64,2},Base.OneTo{Int64}},Array{Int64,1}}}, ::Base.Slice{BlockArrays.BlockedUnitRange{Array{Int64,1}}}, ::Array{Int64,1}) at .\multidimensional.jl:670
   [4] getindex at .\abstractarray.jl:981 [inlined]
   [5] _testvalidity(::BlockBandedMatrices.BlockSkylineMatrix{Float64,Array{Float64,1},BlockBandedMatrices.BlockSkylineSizes{Tuple{BlockArrays.BlockedUnitRange{Array{Int64,1}},BlockArrays.BlockedUnitRange{Array{Int64,1}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},BandedMatrices.BandedMatrix{Int64,Array{Int64,2},Base.OneTo{Int64}},Array{Int64,1}}}) at C:\Users\accou\.julia\dev\SparseDiffTools\test\test_specialmatrices.jl:45
```

**Pull request merged**
