### PR TITLE
Struct for storing graph coloring

### PR DESCRIPTION
**Pull request by pkj-m**
Added a coloring struct to store and pass graph colors
as an argument more succinctly. 
Inspired from coloring in LightGraphs.jl

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
IMO we should really just use a Vector of Integers for this.

**Comment by pkj-m** [comment]
I was thinking using a struct to store/pass the coloring might be a good idea since it'd reflect the data that we're storing in the array more accurately. Plus, the struct itself contains just that array plus an extra value storing the total number of unique colors used.

**Comment by ChrisRackauckas** [comment]
>Plus, the struct itself contains just that array plus an extra value storing the total number of unique colors used.

Yes, but that simplicity is what makes it unnecessary. `color = 1:n` is easy, reflects a dense matrix, and is constant memory. `maximum(color)` does the job for counting colors. We shouldn't make something more complicated than it needs to be.

**Comment by pkj-m** [comment]
Fair enough. Closing.

**Pull request closed without merging**
