### PR TITLE
[WIP] Specialize matrix_colors on different types of matrices

### PR DESCRIPTION
**Pull request by huanglangwen**
- [x] Diagonal (Tridiagonal, SymTridiagonal, Bidiagonal, Diagonal)
- [x] Triangular (UpperTriangular, LowerTriangular)
- [x] BandedMatrices
- [x] BlockBandedMatrices
- [x] BandedBlockBandedMatrices

### CODE REVIEW

**Comment by matthieugomez** [comment]
Looks great! However, it does not seems like there is a specialization to `BandedBlockBandedMatrix` yet, right?

```
using  BlockBandedMatrices, SparseDiffTools
B = BandedBlockBandedMatrix(Zeros(10,10), (1:4,1:4), (2,1), (1,2))
@which matrix_colors(B)
#> matrix_colors(A::AbstractArray{T,2} where T) in SparseDiffTools at /Users/Matthieu/.julia/packages/SparseDiffTools/67zuZ/src/coloring/high_level.jl:15
```

**Comment by ChrisRackauckas** [comment]
Yup missed that one. Thanks!

**Comment by huanglangwen** [comment]
Oops, I forgot this one.

**Comment by huanglangwen** [comment]
Oh, I remember that. The point is the greedy algorithm may be good enough for BandedBlockBandedMatrix.

**Comment by ChrisRackauckas** [comment]
Add a comment explanation.

**Comment by huanglangwen** [comment]
#34

**Pull request merged**
