### PR TITLE
implement jacvec products

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Includes two operators, one for JacVec and another for HesVec.

```julia
f(u) = sum(u.^2)
L = HesVec(f,x)
L*v # (d^2 f/ dx^2) * v
```

and is compatible with IterativeSolvers.jl for Newton-Krylov methods:

```julia
out = similar(v)
gmres!(out, L, v)
```

@pkofod

**Comment by ChrisRackauckas** [comment]
```julia
using SparseDiffTools, BenchmarkTools
const A = rand(300,300)
f(u) = sum(abs2,u)
x = rand(300)
v = rand(300)
du = similar(x)
c1 = similar(x); c2 = similar(x); c3 = similar(x); c4 = similar(x)
cache1 = ForwardDiff.Dual{SparseDiffTools.DeivVecTag}.(x, v)
cache2 = ForwardDiff.Dual{SparseDiffTools.DeivVecTag}.(x, v)
config = ForwardDiff.GradientConfig(f,x)
@btime num_hesvec!($du, $f, $x, $v, $c1, $c3, $c4)
@btime numauto_hesvec!($du, $f, $x, $v, $config, $c1, $c2)
@btime autonum_hesvec!($du, $f, $x, $v, $c1, $cache1, $cache2)
```

shows

```julia 
  49.863 μs (0 allocations: 0 bytes)
  26.216 μs (1 allocation: 16 bytes)
  198.425 μs (0 allocations: 0 bytes)
```

which ones to use :)

**Comment by pkofod** [comment]
Awesome. I’ll use this.

**Comment by pkofod** [comment]
Could there be a hessian one where the uset has the gradient function?

**Comment by ChrisRackauckas** [comment]
HesVecGrad

**Pull request merged**
